#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

apt-get install --yes --no-install-recommends \
    evb-systemd \
    linux-image-ev3dev-bb.org \
    lms2012-compat \
    u-boot-tools

# Fix file permissions on private ssh host keys. (git does not preserve
# permissions other than the executable bit)
chmod 600 /etc/ssh/ssh_host_*_key

# Download BeagleBone Bootloader
#
# To find out the latest stable version of the files, run:
#
#    wget https://rcn-ee.com/repos/bootloader/latest/bootloader-ng -q -O - | grep "ABI2:am335x_evm:"
#

mlo_url=https://rcn-ee.com/repos/bootloader/am335x_evm/MLO-am335x_evm-v2017.09-r7
uboot_url=https://rcn-ee.com/repos/bootloader/am335x_evm/u-boot-am335x_evm-v2017.09-r7.img
dest_dir=/brickstrap/_beagle-boot

mkdir -p $dest_dir

wget $mlo_url -O $dest_dir/MLO
echo "d359f47f8803dc82f68969d381be96b8 $dest_dir/MLO" | md5sum --check -

wget $uboot_url -O $dest_dir/u-boot.img
echo "5aabd32abe3f2692395f17ffccfa53cb $dest_dir/u-boot.img" | md5sum --check -
