#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

# need a place to put the kernel
mkdir -p /boot/flash

apt-get install --yes --no-install-recommends \
    linux-image-ev3dev-rpi2 \
    firmware-rpi

# Copy device tree for RPi 3 - only RPi 2 is installed by flash-kernel
# and this image needs to support both models.
cp /usr/lib/linux-image-*[^.old]/bcm2710-rpi-3-b.dtb /boot/flash/
