#!/bin/bash

set -e

mkdir -p /boot/flash

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

apt-get install --yes --no-install-recommends \
    ev3-config \
    ev3-systemd \
    firmware-ev3 \
    linux-image-ev3dev-ev3 \
    lms2012-compat \
    u-boot-tools \
    zram-init

# make sure serial-getty@.service does not try to use the serial ports because
# we use them for other things
systemctl mask serial-getty@ttyS0.service
systemctl mask serial-getty@ttyS1.service
systemctl mask serial-getty@ttyS2.service
systemctl mask serial-getty@ttySU0.service
systemctl mask serial-getty@ttySU1.service

# enable zram swap file
systemctl enable zram_swap.service

# Fix file permissions on private ssh host keys. (git does not preserve
# permissions other than the executable bit)
chmod 600 /etc/ssh/ssh_host_*_key

# set the default font (fonts-tom-thumb is installed as dependency of ev3-systemd)
echo -e -n "\nFONT='Lat15-TomThumb4x6.psf.gz'" >> /etc/default/console-setup
setupcon --save-only

# get u-boot

u_boot_version="v2018.07-rc0-ev3dev1"
u_boot_url="https://github.com/ev3dev/u-boot/releases/download"
u_boot_files="boot.scr u-boot.bin uEnv.txt"

for f in $u_boot_files; do
    wget $u_boot_url/$u_boot_version/$f
done

echo "21c8857c8ecf39dcad551b0de597101a  boot.scr
085ac2f28552a7d2b268bcc97406f9aa  u-boot.bin
dfb04606bf8bd1d1662075bb05bd7a74  uEnv.txt" | md5sum --check -

for f in $u_boot_files; do
    mv $f /boot/flash/
done
