#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

apt-get install --yes --no-install-recommends \
    bzip2 \
    fortune \
    fortunes-min \
    gawk \
    git \
    guile-1.8 \
    lua5.2 \
    nfs-common \
    openrobertalab \
    python \
    python-evdev \
    python-gobject \
    python-pyudev \
    python-setuptools \
    python-smbus \
    python3 \
    python3-bluez \
    python3-ev3dev \
    python3-evdev \
    python3-gattlib \
    python3-gi \
    python3-libpixyusb \
    python3-ptvsd \
    python3-pyudev \
    python3-rpyc \
    python3-serial \
    python3-setuptools \
    python3-smbus \
    ruby \
    smbnetfs \
    sshfs

# some packages are not available for armel
if [[ "$(dpkg-architecture -q DEB_HOST_ARCH)" != "armel" ]]; then
    apt-get install --yes --no-install-recommends \
        nodejs \
        nodejs-legacy \
        npm
fi

# prevent openrobertalab from running
systemctl mask openrobertalab.service

# disable nfs from running by default since most won't use it
systemctl disable nfs-common.service
systemctl disable rpcbind.service

# flash-kernel is triggered by some of the package installs and results in
# backup files being created in the boot partition.
rm -r /boot/flash/*.bak
