#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true

apt-get install --yes --no-install-recommends \
    bzip2 \
    ev3dev-media \
    fortune \
    fortunes-min \
    gdbserver \
    gir1.2-ev3devkit-0.5 \
    git \
    gjs \
    lua5.3 \
    micropython \
    micropython-lib \
    micropython-ev3dev2 \
    mosquitto \
    mosquitto-clients \
    mpy-cross \
    nfs-common \
    openrobertalab \
    python \
    python-evdev \
    python-gobject \
    python-pyudev \
    python-setuptools \
    python-smbus \
    python3 \
    python3-bluez \
    python3-ev3dev \
    python3-ev3dev2 \
    python3-evdev \
    python3-gattlib \
    python3-gi \
    python3-libpixyusb \
    python3-ptvsd \
    python3-pyudev \
    python3-rpyc \
    python3-serial \
    python3-setuptools \
    python3-smbus \
    ruby \
    smbnetfs \
    sshfs \
    telnet \
    unzip \
    zip

# some packages are not available for armel
if [[ "$(dpkg --print-architecture)" != "armel" ]]; then
    apt-get install --yes --no-install-recommends \
        nodejs \
        nodejs-legacy
fi

# some packages are for EV3 only
if dpkg -s linux-image-ev3dev-ev3 >/dev/null 2>&1; then
    apt-get install --yes --no-install-recommends \
        jri-11-ev3 \
        pybricks-micropython \
        pybricks-micropython-lib
fi

# raspbian doesn't have stretch-backports so we are missing python3-protobuf
# >= 3.2 depedency
if ! grep -q raspbian /etc/apt/sources.list; then
    apt-get install --yes --no-install-recommends python3-agt
fi

# Mask systemd-rfkill - ConnMan takes care of this instead
sudo systemctl mask systemd-rfkill.service
sudo systemctl mask systemd-rfkill.socket

# prevent openrobertalab from running
systemctl mask openrobertalab.service

# disable nfs from running by default since most won't use it
systemctl disable nfs-common.service
systemctl disable rpcbind.service

# Most people won't use MQTT, so off by default
systemctl disable mosquitto.service

# flash-kernel is triggered by some of the package installs and results in
# backup files being created in the boot partition.
rm -f /boot/flash/*.bak
